language: python

python:
  - 3.5
  - 3.6
  - 3.7
  - nightly

install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install codecov

script:
  - pytest --cov=coin_spider
  - codecov --token=bed24858-4b64-4e1c-8106-070d737d512f